config/routes.rb
Rails.application.routes.draw do
  root 'users#index'
  resources :users do
    resources :skill_users
  end
  resources :skills
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/skill.rb
class Skill < ApplicationRecord
  has_many :skill_users, dependent: :destroy
  has_many :users, through: :skill_users
  validates :name, :description, :category, presence: true
end

app/models/skill_user.rb
class SkillUser < ApplicationRecord
  belongs_to :user
  belongs_to :skill
end

app/models/user.rb
class User < ApplicationRecord
  has_many :skill_users, dependent: :destroy
  has_many :skills, through: :skill_users
  validates :name, :email, presence: true
  validates :email, format: { with: /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i }
  validates :email, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/skill_users_controller.rb
class SkillUsersController < ApplicationController
  def new
    @user = User.find(params[:user_id])
    @skill_user = @user.skill_users.new
    @skills = Skill.all
  end

  def create
    @user = User.find(params[:user_id])
    @skill_user = @user.skill_users.new
    @skills = Skill.all
  end

  def destroy
    @user = User.find(params[:user_id])
    @skill_user = @user.skill_users.find(params[:id])
    @skill_user.destroy
    redirect_to @user
  end
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  def index
    @skills = Skill.all
  end

  def new
    @skill = Skill.new
  end

  def create
    @skill = Skill.new(skill_params)
    if @skill.save
      redirect_to skills_path
    else
      render 'new'
    end
  end

  private

  def skill_params
    params.require(:skill).permit(:name, :description, :category)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to @user
    else
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/skill_users_helper.rb
module SkillUsersHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BagdeRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/skills/index.html.erb
<h1>Skills#index</h1>
<p>Find me in app/views/skills/index.html.erb</p>

app/views/skills/new.html.erb
<h1>Skills#new</h1>
<p>Find me in app/views/skills/new.html.erb</p>

app/views/users/index.html.erb
<h1>Current Users</h1>
<%= link_to 'New User', new_user_path %>
<% @users.each do |user| %>
  <p><b>Name</b></p>
  <p><%= user.name %></p>
  <p><b>Email</b></p>
  <p><%= user.email %></p>
<% end %>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>